SupertechLabs/cirq-superstaq

cirq_superstaq/service_test.py

previously `$ check/pytest` and `$ pytest aqt_test.py service_test.py` both worked because aqt_test.py imports `cirq_superstaq.aqt`, but `$ pytest service_test.py` would fail because `cirq_superstaq.aqt.AQTCompilerOutput` was used before the `aqt` submodule was loaded

add import of aqt submodule

---

cirq_superstaq/aqt.py
cirq_superstaq/aqt_test.py
cirq_superstaq/service_test.py

changes required to fix testing and test coverage when qtrl is available in the local environement:
* include "state_jp" and "pulse_list_jp" elements in json_dict passed to `aqt.read_json()` in all tests (aqt_test.py and service_test.py)
* mock qtrl unavailability in `aqt_test.test_read_json()` so that it always functions as if qtrl is not installed
* add `aqt_test.test_read_json_with_qtrl()` to check qtrl functionality (skipped when qtrl is not available)

Support testing with qtrl

---

cirq_superstaq/superstaq_client.py

The `verify` check works. We were comparing the wrong values `super.tech != super.tech/v0.1`

`verify_https` boolean variable

---

cirq_superstaq/custom_gates.py
cirq_superstaq/custom_gates_test.py

(not pressing but has been bothering me)
changes Barrier diagram from:
```
0: ───|───
│
1: ───|───
│
2: ───|───
```
to:
```
0: ───│───
│
1: ───│───
│
2: ───│───
```

clean up Barrier diagram

---

cirq_superstaq/__init__.py
cirq_superstaq/aqt.py
cirq_superstaq/aqt_test.py
cirq_superstaq/serialization.py
cirq_superstaq/serialization_test.py
cirq_superstaq/service.py
cirq_superstaq/service_test.py
cirq_superstaq/superstaq_client_test.py

* add `serialization.(de)serialize_circuits()` functions in anticipation of `v03` API
* use `applications_superstaq.converters.(de)serialize()` wherever possible

Serialization

---

cirq_superstaq/daily_integration_test.py

Changed test to check for all backend strings (ordering is irrelevant). Fixes #63.

fixed test to check for all backends regardless of ordering

---

cirq_superstaq/daily_integration_test.py

D-wave device `d-wave_advantage-system1.1_qpu` retired, Rigetti device `rigetti_aspen-9_qpu` offline. Fixes #112.

Updates integration test to reflect current device statuses

---

examples/finance.ipynb

- changed IBM Q device to `jakarta`
- removed the retired / offline `rigetti` device
- fixed backend names to fit new format

Updates `finance` notebook for new deployment

---

examples/finance.ipynb

Changed d-wave backend

---

cirq_superstaq/daily_integration_test.py

To match deployed version of `GetBackends` endpoint.
As verbalized by @vtomole, the test is indeed showing us the kind of errors we want it to (devices are not taken offline as often as was feared, which would cause the test to fail each time).
Somewhat tangentially related: perhaps it's a good idea to include in the docs standard requirements for deployment? (If that's something we can standardize.)

Updated compile-only devices

---

cirq_superstaq/daily_integration_test.py

Matching backends returned for test user to `daily_integration` test.
Moved https://github.com/SupertechLabs/cirq-superstaq/pull/127 to this -- error turned out not to be a problem with `neutral_atom_qpu`, as those changes (https://github.com/SupertechLabs/SuperstaQ/pull/917#issuecomment-972362675) are not yet merged.

Checking devices accessible to Super.tech users in `daily_integration`

---

cirq_superstaq/service.py
cirq_superstaq/service_test.py

Requires an `ibmq_token` for IBM Q targets. Fixes #119.
This only checks for the token in `create_job`, making token parameter itself in `Service` optional so that clients can run on non-IBM Q devices without needing an IBM Q token.

Added check for an `ibmq_token`

---

cirq_superstaq/custom_gates.py
cirq_superstaq/custom_gates_test.py

... so that if `type(gate) is ParallelRxy`, then `type(gate ** power) is ParallelRxy`, which was not previously the case (and led to a bug in the CQDevice demo).

add __pow__ method to ParallelRxy gate class

---

cirq_superstaq/daily_integration_test.py

Fixes #165. Changed string to match service method return value.

Changed "IBM Q" to "IBMQ", to match expected string

---

cirq_superstaq/__init__.py
cirq_superstaq/custom_gates.py
cirq_superstaq/custom_gates_test.py

gate renamed to avoid conflicts w/ prior usage of "Fermionic SWAP"
parity: SupertechLabs/qiskit-superstaq#100

FermionicSWAPGate -> ZZSwapGate

---

cirq_superstaq/daily_integration_test.py

Fixes #173. ~Added qubit measurement on `cq_compile` test. Whoops, misread the circuit -- the problem wasn't a measurement, but the last `cirq.Z` gate in the hard-coded circuit was applied to the wrong qubit.~ The compiled circuit was a bit different. I'm not sure if this is because of recent changes to `cq_compile` or not.

Edited `cq_compile` circuit

---

cirq_superstaq/daily_integration_test.py

Fixes minor issue in [comment](https://github.com/SupertechLabs/cirq-superstaq/pull/174#issuecomment-1032257038).
Follows [superstaq:#1082](https://github.com/SupertechLabs/SuperstaQ/pull/1082).

remove Z gate that is now annihilated by the CQDevice compiler

---

cirq_superstaq/daily_integration_test.py

Fixes: https://github.com/SupertechLabs/cirq-superstaq/issues/188

`daily_integration_test` for compiling on non-neighboring qubits on `ibmq_compile`

---

cirq_superstaq/daily_integration_test.py

Fixes: https://github.com/SupertechLabs/cirq-superstaq/issues/197

Update `daily_integration_test.py` to check for `pulse_sequence` instead of `pulse`

---

cirq_superstaq/__init__.py

Fixes: https://github.com/SupertechLabs/cirq-superstaq/issues/78

Make `cirq_superstaq.__version__` importable

---

cirq_superstaq/compiler_output.py
cirq_superstaq/compiler_output_test.py
cirq_superstaq/service.py
cirq_superstaq/service_test.py

related to #51, but now that `ibmq_compile` returns both pulse schedules and compiled circuits we can throw a warning but still return the circuits when qiskit isn't installed
also fixes: #200

check for qiskit in ibmq_compile

---

cirq_superstaq/compiler_output.py
cirq_superstaq/compiler_output_test.py
cirq_superstaq/daily_integration_test.py
cirq_superstaq/service_test.py
examples/qscout_compile.ipynb

aligns plurality of `CompilerOutput.jaqal_program(s)` with that of `.circuit(s)` (in line with `qiskit_superstaq.CompilerOutput`)
also corrects `CompulerOutput.__repr__`, however this could definitely use an overhaul (see #103)

support singular `CompilerOutput.jaqal_program`

---

cirq_superstaq/custom_gates.py
cirq_superstaq/custom_gates_test.py

adds `Barrier._trace_distance_bound_()`, which prevents `Barrier` ops from getting dropped by optimization functions like `cirq.DropNegligible()`

prevent cirq optimizations from crossing barriers

---

examples/aqt_compile.ipynb

Renamed for consistency with `download_configs`. (Needs https://github.com/SupertechLabs/applications-superstaq/pull/53)

`save_configs` renamed to `download_configs`

---

cirq_superstaq/serialization.py
cirq_superstaq/serialization_test.py
requirements.txt

This PR gets around https://github.com/quantumlib/Cirq/pull/5189; which is a breaking change.

Patch removal of `device` attribute from `cirq.Circuit()`

---

cirq_superstaq/daily_integration_test.py

Fixes https://github.com/SupertechLabs/cirq-superstaq/issues/243

Use `cirq.testing.assert_circuits_with_terminal_measurements_are_equivalent` for circuit comparison in `daily_integration_test.py`

---

cirq_superstaq/compiler_output.py
cirq_superstaq/service.py
examples/ibmq_compile.ipynb

we now require qiskit-terra >= 0.20.0 for ibmq pulse sequences
(also corrects a docstring)

update qiskit version check

---

requirements.txt

otherwise macos check fails due to https://github.com/python-rapidjson/python-rapidjson/issues/166
should be reverted once `python-rapidjson` has been patched

upper bound python-rapidjson

---

cirq_superstaq/custom_gates.py
cirq_superstaq/custom_gates_test.py
cirq_superstaq/daily_integration_test.py
cirq_superstaq/serialization_test.py

`cirq.MSGate` is not included in `cirq.DEFAULT_RESOLVERS` ([cf.](https://github.com/quantumlib/Cirq/blob/f904a09031b102a3ad5d7b55eff2c8efe565197f/cirq-core/cirq/ops/parity_gates_test.py#L303), as noticed by @vtomole), so reverts [this change](https://github.com/SupertechLabs/cirq-superstaq/pull/282/files#r915085515) and adds corresponding checks to custom_gates_test.py, serialization_test.py, and daily_integration_test.py

fix MSGate deserialization

---

cirq_superstaq/custom_gates.py
cirq_superstaq/custom_gates_test.py

This makes the `css.barrier()` call symmetric to `cirq.measure()`

Changing barrier qubit input from list to unpacked tuple

---

cirq_superstaq/job.py
cirq_superstaq/sampler.py
cirq_superstaq/service.py
requirements.txt

drop support for legacy `cirq.Result`

---

cirq_superstaq/custom_gates_test.py

changes an instance of DropNegligible to drop_negligible_moments so test passes with cirq 1.0.0

cirq 1.0.0
