cirq_superstaq/superstaq_client.py
cirq_superstaq/superstaq_client_test.py

This branch should be merged simultaneously with corresponding PRs in SuperstaQ and qiskit-superstaq.

Rename GetJobs Endpoint

---

cirq_superstaq/service.py
cirq_superstaq/service_test.py
cirq_superstaq/superstaq_client.py
cirq_superstaq/superstaq_client_test.py
examples/aqt_compile.ipynb
setup.py

Fixes: https://github.com/SupertechLabs/cirq-superstaq/issues/15

`upload_aqt_configs` methods and downgrade python from 3.8 to 3.7

---

cirq_superstaq/finance.py
cirq_superstaq/finance_test.py
cirq_superstaq/logistics.py
cirq_superstaq/logistics_test.py
cirq_superstaq/service.py
cirq_superstaq/service_test.py
cirq_superstaq/superstaq_client.py
cirq_superstaq/superstaq_client_test.py

Created a new PR for logistics and finance endpoints. Deleting the old one.

Endpoints created

---

cirq_superstaq/aqt.py
cirq_superstaq/aqt_test.py
cirq_superstaq/service.py
cirq_superstaq/service_test.py

Include pulse_list(s) in AQTCompilerOutput

---

cirq_superstaq/__init__.py
cirq_superstaq/custom_gates.py
cirq_superstaq/custom_gates_test.py

* adds `cirq_superstaq.ParallelGates` custom gate

Parallel gates

---

cirq_superstaq/daily_integration_test.py

Related* to #63 but actually the real fix is server-side
*in the sense that this fix is also needed to make the daily integration test for balance to actually work

ask for float instead of str in get_balance

---

.github/workflows/main.yaml
dev_tools/update-version.sh

Added quotes to environment variable in shell script.

Publish to pypi

---

cirq_superstaq/superstaq_client.py

Fixes: https://github.com/SupertechLabs/cirq-superstaq/issues/53

Don't retry on `500` errors

---

cirq_superstaq/service.py
examples/cirq_superstaq_example.py

Add comments to cirq_superstaq_example.py

---

examples/finance.ipynb

(+ nit: convert docstring to string)

Pass in `qubo` result directly

---

cirq_superstaq/service.py
cirq_superstaq/service_test.py

This reverts commit ea7da561afd9e06ba9e1cc7d425c411efb38c359.

Revert "Added check for an `ibmq_token` (#133)"

---

check/mypy
cirq_superstaq/daily_integration_test.py
cirq_superstaq/service.py
dev-requirements.txt

Fixes: https://github.com/SupertechLabs/cirq-superstaq/issues/125

Add daily integration test for ibmq_compile

---

cirq_superstaq/daily_integration_test.py

Fixes https://github.com/SupertechLabs/cirq-superstaq/issues/202

Loosen pulse duration

---

requirements.txt

necessary for the `aqt_save_configs` endpoint (corresponding qss: supertechlabs/qiskit-superstaq#143)
(we need to add a test for this)

update applications-superstaq req

---

dev-requirements.txt

Fixes: https://github.com/SupertechLabs/cirq-superstaq/issues/254

Update `qiskit-terra` version

---

cirq_superstaq/service.py
setup.cfg

closes: SupertechLabs/applications-superstaq#63 (along with SupertechLabs/qiskit-superstaq#168 and SupertechLabs/applications-superstaq#65)

make `Optional` not optional

---

cirq_superstaq/job.py
cirq_superstaq/job_test.py

Fixes access to shot count

---

cirq_superstaq/daily_integration_test.py
cirq_superstaq/service.py
cirq_superstaq/service_test.py
examples/aqt_compile.ipynb
examples/cirq_superstaq_example.py
examples/cq_compile.ipynb
examples/finance.ipynb
examples/ibmq_compile.ipynb
examples/neutral_atom_compile.ipynb
examples/qscout_compile.ipynb

Make `api_key` first argument in `css.Service` class

---

requirements.txt

Reverts SupertechLabs/cirq-superstaq#289
Fixes https://github.com/SupertechLabs/cirq-superstaq/issues/290

Revert "upper bound python-rapidjson"

---

cirq_superstaq/custom_gates.py
cirq_superstaq/custom_gates_test.py

so that e.g. `css.barrier(q0, q1, q2) == css.barrier(q2, q1, q0)`

Make css.Barrier a cirq.InterchangeableQubitsGate
